name: rails                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-22.04                    # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v2

      - run: echo "This is a build step"

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm -v $(pwd)/src -w /src hysnsec/bundle-audit check --format json --output /src/bundle-audit.json
      - uses: actions/upload-artifact@v4
        name: "Upload bundler-audit artifact"
        with:
          path: /src/bundle-audit.json
        if: always()
        continue-on-error: true

