name: rails                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-22.04                    # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v2

      - run: echo "This is a build step"

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - uses: actions/checkout@v2
      - run: gem install bundler-audit
      - run: export PATH="~/.gem/ruby/2.6.0/bin/:$PATH"
      - run: bundle-audit check --format json --output bundle-audit-output.json
      - uses: actions/upload-artifact@v4
        name: "Upload bundler-audit artifact"
        with:
          path: bundle-audit-output.json
        if: always()
        continue-on-error: true

